=== ma1m2/qa_msl_book_club/src/test/resources/schemas/clubs/create_club_response_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CreateClubResponse",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": { "type": "integer" },
    "bookTitle": { "type": "string" },
    "bookAuthors": { "type": "string" },
    "publicationYear": { "type": "integer" },
    "description": { "type": "string" },
    "telegramChatLink": { "type": "string", "format": "uri" },
    "owner": { "type": "integer" },
    "members": {
      "type": "array",
      "items": { "type": "integer" }
    },
    "reviews": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "created": { "type": "string", "format": "date-time" },
    "modified": { "type": ["string", "null"], "format": "date-time" }
  },
  "required": [
    "id",
    "bookTitle",
    "bookAuthors",
    "publicationYear",
    "description",
    "telegramChatLink",
    "owner",
    "members",
    "reviews",
    "created",
    "modified"
  ]
}

=== ma1m2/qa_msl_book_club/src/test/resources/json/post-club-resp.json
{
  "id": 2922,
  "bookTitle": "Karlsson-on-the-Roof",
  "bookAuthors": "Astrid Lindgren",
  "publicationYear": 42768000,
  "description": "Karlsson is a very short, plump, and overconfident man who lives in a small house hidden behind a chimney on the roof",
  "telegramChatLink": "https://t.me/Sveta2607bot",
  "owner": 6393,
  "members": [
    6393
  ],
  "reviews": [],
  "created": "2026-05-11T10:47:22.640676Z",
  "modified": null
}
