=== ma1m2/qa_msl_book_club/src/test/resources/schemas/review/review_list_respons_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "object",
  "properties": {
    "count": {
      "type": "number"
    },
    "next": {},
    "previous": {},
    "results": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number"
          },
          "club": {
            "type": "number"
          },
          "user": {
            "type": "object",
            "properties": {
              "id": {
                "type": "number"
              },
              "username": {
                "type": "string"
              }
            },
            "required": [
              "id",
              "username"
            ]
          },
          "review": {
            "type": "string"
          },
          "assessment": {
            "type": "number"
          },
          "readPages": {
            "type": "number"
          },
          "created": {
            "type": "string"
          },
          "modified": {}
        },
        "required": [
          "id",
          "club",
          "user",
          "review",
          "assessment",
          "readPages",
          "created",
          "modified"
        ]
      }
    }
  },
  "required": [
    "count",
    "next",
    "previous",
    "results"
  ]
}

=== ma1m2/qa_msl_book_club/src/test/resources/json/review_list_resp.json
{
  "count": 2,
  "next": null,
  "previous": null,
  "results": [
    {
      "id": 13,
      "club": 1,
      "user": {
        "id": 105,
        "username": "Ken_1782311250"
      },
      "review": "Eligendi ducimus odio doloremque ea soluta minima quidem ad quibusdam.",
      "assessment": 3,
      "readPages": 497,
      "created": "2026-06-24T14:27:41.223164Z",
      "modified": null
    },
    {
      "id": 11,
      "club": 1,
      "user": {
        "id": 95,
        "username": "Marya_1782238199"
      },
      "review": "afsfsfsfsafs fasfdflkjl;j;lj;lk ;ljlkjlkj",
      "assessment": 5,
      "readPages": 10,
      "created": "2026-06-24T10:30:47.288424Z",
      "modified": null
    }
  ]
}
